config/routes.rb
Xtoc::Application.routes.draw do

  root 'static_pages#home'

  get '/help'  => 'static_pages#help'
  get '/about' => 'static_pages#about'

end

app/models/logistic_provider.rb
class LogisticProvider < ActiveRecord::Base
  # attr_accessible :address, :name
end

app/models/order.rb
class Order < ActiveRecord::Base
  # attr_accessible :customer_name, :external_id, :invoice_number, :logistic_provider_id, :shipping_address, :tracking_number
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "xtoc"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    %a{href: "http://https://github.com/mdlima/xtoc"} xtoc
    by Marcio Lima

  %nav
    %ul
      %li=link_to "About",   about_path

app/views/layouts/_messages.html.haml
- flash.delete(:timedout)
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
= link_to '/', :class => 'brand', :id => 'toplogo' do
  xtoc
%nav
  %ul.nav.pull-right
    %li
      = link_to 'Home', root_path
    %li
      = link_to 'Help', help_path
    / %li
    /   = link_to "Sign in", '#'
-#  - if user_signed_in?
-#    %li
-#      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
-#  - else
-#    %li
-#      = link_to 'Login', new_user_session_path
-#  - if user_signed_in?
-#    %li
-#      = link_to 'Edit account', edit_user_registration_path
-#    - if current_user.has_role? :admin
-#      %li
-#        = link_to 'Admin', users_path
-#  - else
-#    %li
-#      = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Xtoc</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!! 5
/[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en">
/[if IE 7] <html class="no-js lt-ie9 lt-ie8" lang="en">
/[if IE 8] <html class="no-js lt-ie9" lang="en">
<!--[if gt IE 8]><!-->
%html.no-js{:lang => 'en'}
  / <![endif]
  %head
    %meta{:charset => 'utf-8'}/
    %meta{:content => 'IE=edge,chrome=1', 'http-equiv' => 'X-UA-Compatible'}/
    
    %meta{:content => (content_for?(:description) ? yield(:description) : 'xtoc, simple warehouse management system.'), :name => 'description'}/
    %meta{:content => 'Marcio Lima', :name => 'author'}/
    
    %meta{:content => 'width=device-width', :name => 'viewport'}/
    %meta{:content => 'yes', :name => 'apple-mobile-web-app-capable'}/
    %meta{:content => 'black-translucent', :name => 'apple-mobile-web-app-status-bar-style'}/
    
    %title
      = full_title(yield(:title))
    
    = stylesheet_link_tag 'application', :media => 'all', 'data-turbolinks-track' => true
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    = csrf_meta_tags
    = yield :head
    = javascript_include_tag 'application', 'data-turbolinks-track' => true #, :async => true

  %body
    /[if lt IE 7] <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
    %header.navbar.navbar-fixed-top.navbar-inverse
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'

    #main{:role => 'main'}
      .container
        = render 'layouts/messages'
        = yield
        = render 'layouts/footer'

      / ! end of .container
    / ! end of #main
    

app/views/static_pages/about.html.haml
~ provide(:title, 'About')
%h1 About
%p This is the about page for the <strong>xtoc</strong> app.

app/views/static_pages/help.html.haml
~ provide(:title, 'Help')
%h1 Help
%p This is the help page for the <strong>xtoc</strong> app.

app/views/static_pages/home.html.haml
.center.hero-unit
  %h1 Home

  %h2
    This is the home page for the
    %a{href: "http://railstutorial.org/"} Ruby on Rails Tutorial
    sample application.

  = link_to "Sign up now!", '#', class: "btn btn-large btn-primary"

= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/'